apiVersion: v1
kind: Namespace
metadata:
  name: tsaf-monitoring
  labels:
    name: tsaf-monitoring
    app.kubernetes.io/name: tsaf-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: tsaf

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: tsaf-monitoring
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "20"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: tsaf-monitoring
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container