apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsaf-service-account
  namespace: tsaf
  labels:
    app: tsaf
    component: rbac
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsaf-role
  namespace: tsaf
  labels:
    app: tsaf
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tsaf-role-binding
  namespace: tsaf
  labels:
    app: tsaf
    component: rbac
subjects:
- kind: ServiceAccount
  name: tsaf-service-account
  namespace: tsaf
roleRef:
  kind: Role
  name: tsaf-role
  apiGroup: rbac.authorization.k8s.io